### ISSUE TITLE
Deleted my whole system 

### ISSUE THREAD

**Issue by voidcoefficient** [landley/mkroot#12]
I don't know yet how, but running the main script deleted my whole system (using user privileges).

**Comment by voidcoefficient** [comment]
Probably happened because of line 200 not having a sanity check
rm -rf "$ROOT" &&
Also, I don't see where $ROOT is being defined. I had my machine turned on for hours working on some projects so maybe something was set. Or Bedrock set it. Lost months of work, someone should look into it

**Comment by landley** [comment]
ROOT is set on line 70: https://github.com/landley/mkroot/blob/master/mkroot.sh#L70

(See line 64 for an explanation.) It allows you to override it, but it won't just take one from your environment because we blank the environment (starting on line 19):

\# Clear environment variables by restarting script w/bare minimum passed through
[ -z "$NOCLEAR" ] &&
  exec env -i NOCLEAR=1 HOME="$HOME" PATH="$PATH" $(env | grep -i _proxy=) \
    CROSS_COMPILE="$CROSS_COMPILE" CROSS_SHORT="$CROSS_SHORT" "$0" "$@"

I.E. the script allows you to override the output directory by setting ROOT (and yes, it blanks the directory you point it at), but it will _only_ let you do so from the command line (./mkroot.sh ROOT=blah) because it blanks the inherited environment, unless you export NOCLEAR yourself.

So in order for what you described happening to happen, you'd have to 1) export NOCLEAR, 2) export ROOT=~

Is that what you did? If not, do you see some other way for what you described to happen?

Rob

**Comment by landley** [comment]
PS: rm -rf "" is a NOP (with both toybox rm and debian rm). According to strace it's doing:

unlink("")                              = -1 ENOENT (No such file or directory)

But the -f disables error reporting for that. So if $ROOT wasn't set, nothing would get deleted by the line you highlighted. If ROOT _is_ set to an existing directory on line 200 (having made it through lines 19 and 70) what "sanity check" would you recommend I add to line 200?

**Comment by landley** [comment]
2+ weeks with no response, calling it pilot error.
