### ISSUE TITLE
"./mkroot.sh dropbear" fails

### ISSUE THREAD

**Issue by kt97679** [landley/mkroot#4]
When I try to run
<pre>
./mkroot.sh dropbear
</pre>
build fails with the following error:
module/dropbear: line 34: strip: command not found
If I understand correctly this happens because toybox doesn't contain strip command. Build works with following diff:
<pre>
diff --git a/module/dropbear b/module/dropbear
index 7cdf596..115bf0b 100755
--- a/module/dropbear
+++ b/module/dropbear
@@ -31,7 +31,7 @@ CFLAGS="-I $ZLIB -Os" LDFLAGS="--static -L $ZLIB" ./configure \
   --host=${CROSS_BASE%-} &&
 sed -i 's@/usr/bin/dbclient@ssh@' options.h &&
 make -j $(nproc) PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" MULTI=1 SCPPROGRESS=1 &&
-${CROSS_COMPILE}strip dropbearmulti &&
+/usr/bin/strip dropbearmulti &&
 mkdir -p "$ROOT/bin" &&
 cp dropbearmulti "$ROOT"/bin || exit 1
 for i in "$ROOT"/bin/{ssh,sshd,scp,dropbearkey}
</pre>

**Comment by landley** [comment]
On 05/25/2017 01:40 PM, kt97679 wrote:
> When I try to run
> 
> ./mkroot.sh dropbear
> 
> build fails with the following error:
> module/dropbear: line 34: strip: command not found
> If I understand correctly this happens because toybox doesn't contain
> strip command.

Ah. The toybox "make install_airlock" doesn't symlink to the host strip
because the build should be using the target-prefixed strip. (Same
reason it doesn't install the host readelf and thus:

http://lkml.iu.edu/hypermail/linux/kernel/1705.2/04194.html

But if you're _not_ cross compiling then it needs the host version of
both tools!

Hmmm... possibly it should only use the airlock step when it's cross
compiling?

 Build works with following diff:
> 
> diff --git a/module/dropbear b/module/dropbear
> index 7cdf596..115bf0b 100755
> --- a/module/dropbear
> +++ b/module/dropbear
> @@ -31,7 +31,7 @@ CFLAGS="-I $ZLIB -Os" LDFLAGS="--static -L $ZLIB" ./configure \
>    --host=${CROSS_BASE%-} &&
>  sed -i 's@/usr/bin/dbclient@ssh@' options.h &&
>  make -j $(nproc) PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" MULTI=1 SCPPROGRESS=1 &&
> -${CROSS_COMPILE}strip dropbearmulti &&
> +/usr/bin/strip dropbearmulti &&

Wrong fix, but I checked in a different one.

Thanks for the heads up.

Rob

**Comment by kt97679** [comment]
Works now, thanks a lot for the fix!
