### ISSUE TITLE
"/bin/sh: 1: bc: not found" when building the kernel

### ISSUE THREAD

**Issue by tgarm** [landley/mkroot#5]
The command is:

> ./cross.sh armv5l ./mkroot.sh kernel

It goes wrong with the following prompt:
>/bin/sh: 1: bc: not found
Kbuild:67: recipe for target 'include/generated/timeconst.h' failed
make[1]: *** [include/generated/timeconst.h] Error 127
Makefile:1047: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2

Host system:
- Ubuntu 16.04.2 Server in Virtualbox
- **mkroot** and **mcm** in home directory
- **bc** installed via `sudo apt-get install bc`
- `~/mkroot/mcm-buildall.sh` executed in **mcm** directory and toolchains were generated
- build kernel version 4.11

Further check:
- add `V=1` in line 250,251 of module/kernel, and found the latest command which met error is:
>set -e; : '  CHK     include/generated/timeconst.h'; mkdir -p include/generated/; 	(echo 100 | bc -q kernel/time/timeconst.bc ) < kernel/time/timeconst.bc > include/generated/timeconst.h.tmp; if [ -r include/generated/timeconst.h ] && cmp -s include/generated/timeconst.h include/generated/timeconst.h.tmp; then rm -f include/generated/timeconst.h.tmp; else : '  UPD     include/generated/timeconst.h'; mv -f include/generated/timeconst.h.tmp include/generated/timeconst.h; fi

- try this single command line in `build/armv5l-linux-musleabihf-tmp/linux-4.11/`, no error generated

**Comment by landley** [comment]
On 05/30/2017 08:31 PM, Simon Ding wrote:
> The command is:
> 
>     ./cross.sh armv5l ./mkroot.sh kernel
> 
> It goes wrong with the following prompt:
> 
>     /bin/sh: 1: bc: not found
>     Kbuild:67: recipe for target 'include/generated/timeconst.h' failed
>     make[1]: *** [include/generated/timeconst.h] Error 127
>     Makefile:1047: recipe for target 'prepare0' failed
>     make: *** [prepare0] Error 2

You need the new version of toybox. Currently the commit is in git:


https://github.com/landley/toybox/commit/9be140ebb29f92be2b3924eb1442b38a9e062966

The next toybox release is scheduled for the 1st (thursday), I can
update the download line once there's a tarball URL.

In the meantime, you can go:

  cd download
  git clone https://github.com/landley/toybox

Then it should use the git directory instead of the tarball.

Rob

**Comment by tgarm** [comment]
Thank you! It works when I use the toybox git code.
